version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 91:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: regenschirm13
      WORDPRESS_DB_NAME: wordpress
    networks:
      - back

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: regenschirm13
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
     - back

networks:
   back:


